# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YXLiveApp' do
 pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage', '~> 3.7.4’
  pod 'MJExtension', '~> 3.0.13'
 pod 'ReactiveCocoa', '~> 2.5’

end
